import fs from 'fs';
import fsp from 'fs/promises';
import os from 'os';
import path from 'path';
import { randomUUID } from 'crypto';
import {
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
  HeadObjectCommand,
} from '@aws-sdk/client-s3';
import { getSignedUrl as presignUrl } from '@aws-sdk/s3-request-presigner';
import env from '../config/env.js';
import getR2Client from '../config/r2.client.js';

/**
 * ============================================================================
 * storage.service.js — single storage abstraction for the whole backend.
 * ============================================================================
 *
 * Nothing outside this file should call `fs.readFileSync`, `fs.existsSync`,
 * `fs.createReadStream`, etc. on an *uploaded/generated asset* (timesheets,
 * invoices, templates, signatures, stamps, logos). Business logic (invoice
 * generation, AI extraction, downloads, ...) only ever talks to the methods
 * exported from here, and never needs to know or care whether
 * STORAGE_DRIVER is "local" or "r2".
 *
 * Concepts:
 *  - "key": the tenant-scoped relative key, e.g. companies/{id}/{folder}/{file}.
 *    For the local driver this is exactly the same string used as the web
 *    path (with a leading slash stripped). For r2 it's the literal S3 object
 *    key. FileRecord.storageKey / FileRecord.path both resolve to this.
 *  - "driver": 'local' | 'r2'. Every method accepts an explicit driver so
 *    per-record drivers (old local records alongside new r2 records) keep
 *    working after a cutover; if omitted it falls back to STORAGE_DRIVER.
 */

const storageRoot = path.resolve(process.cwd(), 'src', 'storage');
const tempRoot = path.join(os.tmpdir(), 'crewcontrol-storage-tmp');

const isR2 = () => env.storage.driver === 'r2';
const resolveDriver = (driver) => driver || (isR2() ? 'r2' : 'local');

/**
 * Every object key is scoped under the owning company (or owner, for the
 * rare record with no company yet). This is what actually prevents one
 * tenant from ever being able to reach another tenant's files - the app
 * never trusts a client-supplied path, only the companyId/ownerId taken
 * from the authenticated request.
 *
 *   companies/{companyId}/{folder}/{filename}
 *   owners/{ownerId}/{folder}/{filename}          (no company yet)
 */
export const buildTenantKey = ({ companyId, ownerId, folder, filename }) => {
  const safeFolder = String(folder || 'misc').replace(/[^a-zA-Z0-9_-]/g, '');
  const safeFilename = String(filename || 'file').replace(/[^a-zA-Z0-9._-]/g, '_');
  const scope = companyId ? `companies/${companyId}` : `owners/${ownerId}`;
  return `${scope}/${safeFolder}/${safeFilename}`;
};

// A "key" and a local web-path ("/companies/...") refer to the same object;
// normalize away the leading slash so both forms work everywhere below.
const normalizeKey = (keyOrWebPath) => String(keyOrWebPath || '').replace(/^\/+/, '');

// D19.8 finding (defense-in-depth, not currently exploitable): every
// caller of this function today passes a key that was either generated by
// buildTenantKey() above (which strips `/` and any `..`-forming character
// from both the folder and filename segments before they're ever joined)
// or read back from a FileRecord document written that way - confirmed via
// repository-wide search of every objectExists/getObjectBuffer/
// downloadToTempFile/streamObject caller. But nothing in this function
// itself enforces that invariant; a future caller passing an unsanitized
// key (a `../../../etc/passwd`-style value) would resolve to a real path
// outside storageRoot with no defense at this layer. path.join() happily
// resolves `..` segments, so a plain prefix concatenation isn't enough -
// this checks the final resolved path is still actually inside
// storageRoot and throws otherwise, same trust-nothing-twice principle as
// the rest of this file's write path.
const keyToLocalAbsolutePath = (key) => {
  const resolved = path.resolve(storageRoot, normalizeKey(key));
  const rootWithSep = storageRoot.endsWith(path.sep) ? storageRoot : `${storageRoot}${path.sep}`;
  if (resolved !== storageRoot && !resolved.startsWith(rootWithSep)) {
    throw new Error('Resolved storage path escapes storageRoot');
  }
  return resolved;
};

/**
 * Infer the driver a previously-stored path/key was written with, for the
 * (common, expected) case where the caller only has the plain string that
 * was persisted on a document and not a FileRecord with an explicit
 * storageDriver field. Local paths always start with '/', r2 keys never do.
 * Always prefer an explicit driver (e.g. FileRecord.storageDriver) over this
 * when one is available.
 */
export const driverFromStoredPath = (storedPath) => {
  const value = String(storedPath || '');
  if (!value) return resolveDriver();
  return value.startsWith('/') ? 'local' : 'r2';
};

const ensureLocalDir = async (dirPath) => {
  await fsp.mkdir(dirPath, { recursive: true });
};

const streamToBuffer = async (stream) => {
  const chunks = [];
  for await (const chunk of stream) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  return Buffer.concat(chunks);
};

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

/**
 * Save a buffer (e.g. from multer memoryStorage) under a tenant-scoped key.
 * Returns { driver, key, path } where `path` is what gets stored on the
 * FileRecord/Invoice document - a local web path for 'local', the R2 key
 * for 'r2'.
 */
export const saveBuffer = async ({ companyId, ownerId, folder, filename, buffer, mimetype }) => {
  const key = buildTenantKey({ companyId, ownerId, folder, filename });

  if (isR2()) {
    const client = getR2Client();
    await client.send(
      new PutObjectCommand({
        Bucket: env.storage.r2.bucket,
        Key: key,
        Body: buffer,
        ContentType: mimetype || 'application/octet-stream',
      })
    );
    return { driver: 'r2', key, path: key };
  }

  // local fallback - identical behavior to the original disk storage
  const absPath = keyToLocalAbsolutePath(key);
  await ensureLocalDir(path.dirname(absPath));
  await fsp.writeFile(absPath, buffer);
  return { driver: 'local', key, path: `/${key}` };
};

/**
 * Persist a file that some other library already wrote to a *local working
 * path* (pdf-lib / pdfkit both need a real filesystem path to write to).
 * This always routes through saveBuffer, so both drivers behave identically
 * no matter where the source file physically lives (storageRoot, an OS temp
 * dir, whatever) - there's no more special-casing based on path location.
 * The caller owns cleanup of `absolutePath` (see cleanupTempFile).
 */
export const saveLocalFile = async ({ absolutePath, companyId, ownerId, folder, filename }) => {
  const finalFilename = filename || path.basename(absolutePath);
  const buffer = await fsp.readFile(absolutePath);
  const mimetype = finalFilename.toLowerCase().endsWith('.pdf')
    ? 'application/pdf'
    : 'application/octet-stream';
  return saveBuffer({ companyId, ownerId, folder, filename: finalFilename, buffer, mimetype });
};

// ---------------------------------------------------------------------------
// Read
// ---------------------------------------------------------------------------

export const objectExists = async ({ key, driver } = {}) => {
  const d = resolveDriver(driver);
  const k = normalizeKey(key);
  if (!k) return false;

  if (d === 'r2') {
    try {
      const client = getR2Client();
      await client.send(new HeadObjectCommand({ Bucket: env.storage.r2.bucket, Key: k }));
      return true;
    } catch {
      return false;
    }
  }

  return fs.existsSync(keyToLocalAbsolutePath(k));
};

export const getObjectBuffer = async ({ key, driver } = {}) => {
  const d = resolveDriver(driver);
  const k = normalizeKey(key);

  if (d === 'r2') {
    const client = getR2Client();
    const result = await client.send(new GetObjectCommand({ Bucket: env.storage.r2.bucket, Key: k }));
    return streamToBuffer(result.Body);
  }

  return fsp.readFile(keyToLocalAbsolutePath(k));
};

/**
 * Some libraries (pdf-lib, pdfplumber/OCR via the AI microservice, etc.)
 * need a real filesystem path, not a buffer. This gets the object onto
 * local disk when needed and hands back a path plus a cleanup() you MUST
 * call when done.
 *
 * For the local driver this is a zero-copy no-op: it just resolves the
 * already-existing absolute path, and cleanup() does nothing - local mode
 * behaves exactly as it always did.
 */
export const downloadToTempFile = async ({ key, driver, filename } = {}) => {
  const d = resolveDriver(driver);
  const k = normalizeKey(key);

  if (d === 'local') {
    const absolutePath = keyToLocalAbsolutePath(k);
    return { path: absolutePath, isTemp: false, cleanup: async () => {} };
  }

  const buffer = await getObjectBuffer({ key: k, driver: 'r2' });
  await ensureLocalDir(tempRoot);
  const safeName = String(filename || path.basename(k) || 'file').replace(/[^a-zA-Z0-9._-]/g, '_');
  const tempPath = path.join(tempRoot, `${randomUUID()}-${safeName}`);
  await fsp.writeFile(tempPath, buffer);
  return { path: tempPath, isTemp: true, cleanup: async () => cleanupTempFile(tempPath) };
};

/**
 * Same idea as downloadToTempFile but hands back an isolated, disposable
 * temp *directory* containing the file - useful for pipelines that write
 * sibling artifacts (OCR debug images, extracted pages, etc.) next to the
 * source file. Works uniformly for both drivers (local mode gets a real
 * copy in an isolated dir too, so callers never have to special-case it).
 */
export const downloadToTempDirectory = async ({ key, driver, filename } = {}) => {
  const d = resolveDriver(driver);
  const k = normalizeKey(key);
  await ensureLocalDir(tempRoot);
  const dir = await fsp.mkdtemp(path.join(tempRoot, 'dir-'));
  const safeName = String(filename || path.basename(k) || 'file').replace(/[^a-zA-Z0-9._-]/g, '_');
  const destPath = path.join(dir, safeName);

  if (d === 'local') {
    await fsp.copyFile(keyToLocalAbsolutePath(k), destPath);
  } else {
    const buffer = await getObjectBuffer({ key: k, driver: 'r2' });
    await fsp.writeFile(destPath, buffer);
  }

  return { dir, path: destPath, cleanup: async () => cleanupTempDirectory(dir) };
};

/**
 * A time-limited, access-controlled download URL. R2 only - callers on the
 * local driver should use streamObject() instead. Access control must
 * already have been checked by the caller (see files.controller.js) before
 * a URL is handed back; this call doesn't know or care who's asking.
 */
export const getSignedUrl = async ({ key, driver, expiresIn } = {}) => {
  const d = resolveDriver(driver);
  if (d !== 'r2') {
    throw new Error('getSignedUrl() is only supported for the r2 driver');
  }
  const client = getR2Client();
  const command = new GetObjectCommand({ Bucket: env.storage.r2.bucket, Key: normalizeKey(key) });
  return presignUrl(client, command, {
    expiresIn: expiresIn || env.storage.r2.signedUrlExpirySeconds,
  });
};

/**
 * Stream an object straight into an Express response. Used by download
 * endpoints so they never need to touch fs / R2 clients directly.
 */
export const streamObject = async ({ key, driver, res, contentType, disposition } = {}) => {
  const d = resolveDriver(driver);
  const k = normalizeKey(key);

  if (contentType) res.setHeader('Content-Type', contentType);
  if (disposition) res.setHeader('Content-Disposition', disposition);

  if (d === 'r2') {
    const client = getR2Client();
    const result = await client.send(new GetObjectCommand({ Bucket: env.storage.r2.bucket, Key: k }));
    await new Promise((resolve, reject) => {
      result.Body.on('error', reject);
      res.on('finish', resolve);
      res.on('error', reject);
      result.Body.pipe(res);
    });
    return;
  }

  const absolutePath = keyToLocalAbsolutePath(k);
  await new Promise((resolve, reject) => {
    const stream = fs.createReadStream(absolutePath);
    stream.on('error', reject);
    res.on('finish', resolve);
    res.on('error', reject);
    stream.pipe(res);
  });
};

/**
 * Access-controlled retrieval, kept for callers that want a redirect (r2) or
 * a stream-it-yourself path (local) rather than having streamObject() write
 * the response directly. Caller MUST have already verified the requester
 * owns/has-access-to this record - this only decides HOW to fetch the
 * bytes, not WHO can ask.
 */
export const getAccessUrlOrPath = async ({ key, driver } = {}) => {
  const d = resolveDriver(driver);
  if (d === 'r2') {
    const url = await getSignedUrl({ key, driver: 'r2' });
    return { type: 'redirect', url };
  }
  return { type: 'stream', absolutePath: keyToLocalAbsolutePath(normalizeKey(key)) };
};

// ---------------------------------------------------------------------------
// Delete / cleanup
// ---------------------------------------------------------------------------

export const deleteObject = async ({ key, driver } = {}) => {
  const d = resolveDriver(driver);
  const k = normalizeKey(key);

  if (d === 'r2') {
    const client = getR2Client();
    await client.send(new DeleteObjectCommand({ Bucket: env.storage.r2.bucket, Key: k }));
    return;
  }

  const absPath = keyToLocalAbsolutePath(k);
  if (fs.existsSync(absPath)) await fsp.unlink(absPath);
};

/** Safe to call on any path (temp or otherwise); never throws. */
export const cleanupTempFile = async (filePath) => {
  if (!filePath) return;
  try {
    await fsp.unlink(filePath);
  } catch (error) {
    if (error?.code !== 'ENOENT') {
      console.error('cleanupTempFile failed:', error.message);
    }
  }
};

/** Safe to call on any directory; never throws. */
export const cleanupTempDirectory = async (dirPath) => {
  if (!dirPath) return;
  try {
    await fsp.rm(dirPath, { recursive: true, force: true });
  } catch (error) {
    console.error('cleanupTempDirectory failed:', error.message);
  }
};

/**
 * Reserve a fresh path inside the shared temp root for a working file this
 * process is about to create (e.g. a freshly rendered invoice PDF), without
 * downloading anything. Caller writes to it, then typically calls
 * saveLocalFile() to persist the result and cleanupTempFile() to remove the
 * working copy - this keeps generated output out of the permanent local
 * storage tree entirely, so nothing generated is ever left behind on disk
 * for either driver.
 */
export const reserveTempFilePath = async (filename) => {
  await ensureLocalDir(tempRoot);
  const safeName = String(filename || 'file').replace(/[^a-zA-Z0-9._-]/g, '_');
  return path.join(tempRoot, `${randomUUID()}-${safeName}`);
};

export default {
  buildTenantKey,
  driverFromStoredPath,
  saveBuffer,
  saveLocalFile,
  objectExists,
  getObjectBuffer,
  downloadToTempFile,
  downloadToTempDirectory,
  getSignedUrl,
  streamObject,
  getAccessUrlOrPath,
  deleteObject,
  cleanupTempFile,
  cleanupTempDirectory,
  reserveTempFilePath,
};
